backBtn.onclick=()=>{
   location.href="/index.html"
}
window.onload=()=>{
  theme(html,localStorage.getItem("theme"))
  select.value=localStorage.getItem("charLength")
  roles.forEach((r)=>{
   if (r.childNodes[1].alt==localStorage.getItem('pgRole')) {
      r.classList.add("border")
   }
  })
}
roles.forEach((r)=>{
   r.onclick=()=>{
      localStorage.setItem("pgRole",r.childNodes[1].alt)
      location.href="/index.html"
   }
})
select.onclick=()=>{
   localStorage.setItem("charLength",select.value)
}